### ISSUE TITLE
Call create_db before run

### ISSUE THREAD

**Issue by eoinieo** [testdrivenio/flask-ses-rq#2]
UPDATE:
I've just seen on your website that you did recommend this CLI call to be used before registering a user, apologies!
>> docker-compose run users python manage.py create_db

Hi Michael,

Firstly, big thanks for this repo, using boto to send my emails is way easier than setting up a sendmail/postfix scenario.

Secondly, tiny suggestion, not even worth forking for it. This repo failed straight out of the box because the user table doesn't exist. Altering docker-compose.yml line:11 to
command: ash -c 'python manage.py create_db ; python manage.py run -h 0.0.0.0'
fixes that.

KR,
Eoin

**Comment by mjhea0** [comment]
Apologies for the delay. I just updated the blog post, code, and README. Cheers!
